module Flan
  module ViewHelpers
    def flan_command(key)
      match = /flan_(.*)/.match(key.to_s)
      raise ArgumentError.new("#{key} wasn't generated by Flan") unless match
      "_track#{match[1].capitalize}"
    end

    def flan_js
      js = []
      flan_keys.each do |key|
        flash[key].each do |page|
          js << "_gaq.push(['#{flan_command(key)}', '#{flan_path(page)}']);"
        end
      end
      js.empty? ? '' : content_tag(:script, js.join("\n"),
                                   :type => 'text/javascript')
    end

    def flan_keys
      flan_keys = flash.keys.select{|k| k.to_s =~ /^flan_/}
    end

    def flan_path(path)
      "/_virtual/#{path}".gsub('//', '/')
    end
  end
end
